Factory/Models/Machine.cs
using System.Collections.Generic;

namespace Factory.Models
{
  public class Machine
  {
    public Machine()
    {
      this.JoinEntities = new HashSet<EngineerMachine>();
    }

    public int MachineId { get; set; }
    public string Name { get; set; }
    public int SerialNumber { get; set; }
    public bool Operational { get; set; }
    public virtual ICollection<EngineerMachine> JoinEntities { get; set; }
  }
}

Factory/Controllers/MachinesController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;

namespace Factory.Controllers
{
  public class MachinesController : Controller
  {
    private readonly FactoryContext _db;

    public MachinesController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index ()
    {
      List<Machine> model = _db.Machines.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Machine machine)
    {
      _db.Machines.Add(machine);
      _db.SaveChanges();

      return RedirectToAction("Index");
    }
    
    public ActionResult Details(int id)
    {
      var thisMachine = _db.Machines
          .Include(machine => machine.JoinEntities)
          .ThenInclude(join => join.Engineer)
          .FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    public ActionResult Edit(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult Edit(Machine machine)
    {
      _db.Entry(machine).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      _db.Machines.Remove(thisMachine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    } 
    [HttpPost]
    public ActionResult DeleteEngineer(int joinId)
    {
      var joinEntry = _db.EngineerMachine.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
      _db.EngineerMachine.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult AddEngineer(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "Name");
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult AddEngineer(Machine machine, int EngineerId)
    {
      if (EngineerId != 0)
      {
      _db.EngineerMachine.Add(new EngineerMachine() { EngineerId = EngineerId, MachineId = machine.MachineId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    // Updates 'Operational' bool and returns the same view
    public ActionResult Repair(int machineId)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == machineId);
      if (thisMachine.Operational)
      {
        thisMachine.Operational = false;
      }
      else
      {
        thisMachine.Operational = true;
      }
      _db.Entry(thisMachine).State = EntityState.Modified;
      _db.SaveChanges();
      return View("Details", thisMachine);
    }
  }
}

Factory/Views/Machines/AddEngineer.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<div class="jumbotron">
<h2>Add an engineer</h2>
</div>

<h4>Add an engineer for this machine: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.MachineId)

  @Html.Label("Select engineer")
  @Html.DropDownList("EngineerId")

  <input type="submit" value="Save" />
}
<div id="footer">
<button style="height:100px; width:250px; font-size:20px;">@Html.ActionLink("Back to list", "Index")</button>
</div>

Factory/Views/Machines/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<div class="jumbotron">
<h4>Add a new machine</h4>
</div>

<div class="row">
  <div class="col-md-4">
    <div class="card">
      @using (Html.BeginForm())
      {
        @Html.LabelFor(model => model.Name)
        <br>
        @Html.TextBoxFor(model => model.Name)
        <br>
        @Html.LabelFor(model => model.SerialNumber)
        <br>
        @Html.TextBoxFor(model => model.SerialNumber)
        <br>
        @Html.LabelFor(model => model.Operational)
        <br>
        @Html.EditorFor(model => model.Operational)
        <br>

        <input type="submit" value="Add new machine" />
      }
    </div>
  </div>
</div>

<div id="footer">
<button style="height:100px; width:250px; font-size:20px;">@Html.ActionLink("Show all machines", "Index")</button>
</div>

Factory/Views/Machines/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}

<div id="footer">
<button style="height:100px; width:250px; font-size:20px;">@Html.ActionLink("Back to List", "Index")</button>
</div>

Factory/Views/Machines/Details.cshtml
@{
  Layout = "_Layout";
}
@using Factory.Models;
@model Factory.Models.Machine;

<div class="jumbotron">
<h2>Machine Details</h2>
</div>

<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>
<h3>@Html.DisplayNameFor(model => model.SerialNumber): @Html.DisplayFor(model => model.SerialNumber)</h3>

@if(@Model.JoinEntities.Count == 0)
{
  <p>This machine is not assigned to any engineers.</p>
  <p>Assign an engineer to view machine status.</p>
}
else
{
  <h4>Engineers assigned to @Model.Name:</h4>
  <ul>
  @foreach(var join in Model.JoinEntities)
  {
    <li>@join.Engineer.Name</li>
      @using (Html.BeginForm("DeleteEngineer", "Machines"))
    {
      @Html.Hidden("joinId", @join.EngineerMachineId)
      <input type="submit" value="Delete"/>
    }
  }
  </ul>

  <h4>Machine status:</h4>
  @if(Model.Operational)
  {
    @using(@Html.BeginForm("Repair", "Machines"))
    {
      @Html.Hidden("machineId", @Model.MachineId)
      <input type="submit" value="Operational. Report needing repairs" class="btn btn-primary">
    }
  }
  @if(!Model.Operational)
  {
    @using(@Html.BeginForm("Repair", "Machines"))
    {
      @Html.Hidden("machineId", @Model.MachineId)
      <input type="submit" value="Offline. Click to repair" class="btn btn-primary">
    }
  }
}

<div id="footer">
<button style="height:100px; width:250px; font-size:20px;">@Html.ActionLink("Back to machines", "Index")</button>
<button style="height:100px; width:250px; font-size:20px;">@Html.ActionLink("Add an engineer", "AddEngineer", new { id = Model.MachineId })</button>
<button style="height:100px; width:250px; font-size:20px;">@Html.ActionLink("Edit Machine", "Edit", new { id = Model.MachineId })</button>
<button style="height:100px; width:250px; font-size:20px;">@Html.ActionLink("Delete Machine", "Delete", new { id = Model.MachineId })</button>
</div>

Factory/Views/Machines/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<div class="jumbotron">
<h2>Edit</h2>
</div>

<h4>Edit this machine: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.MachineId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  @Html.LabelFor(model => model.SerialNumber)
  @Html.EditorFor(model => model.SerialNumber)

  <input type="submit" value="Save" />
}

<div id="footer">
<button style="height:100px; width:250px; font-size:20px;">@Html.ActionLink("Back to list", "Index")</button>
</div>

Factory/Views/Machines/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;

<div class="jumbotron">
<h1>Machines</h1>
</div>

@if (@Model.Count == 0)
{
  <h3>No machines have been added yet!</h3>
} 

<ul>
  @foreach(Machine machine in Model)
  {
    <li>@Html.ActionLink($"{machine.Name}", "Details", new { id = machine.MachineId })</li>
  }
</ul>

<div id="footer">
<button style="height:100px; width:250px; font-size:20px;">@Html.ActionLink("Home", "Index", "Home")</button>
<button style="height:100px; width:250px; font-size:20px;">@Html.ActionLink("Add new machine", "Create")</button>
</div>