Factory/Models/Engineer.cs
using System.Collections.Generic;
using System;

namespace Factory.Models
{
  public class Engineer
  {
    public Engineer()
    {
      this.JoinEntities = new HashSet<EngineerMachine>();
    }
    public int EngineerId { get; set; }
    public string Name { get; set; }
    public DateTime RepairMade { get; set; }
    public virtual ICollection<EngineerMachine> JoinEntities { get; }
  }
}

Factory/Controllers/EngineersController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;

namespace Factory.Controllers
{
  public class EngineersController : Controller
  {
    private readonly FactoryContext _db;

    public EngineersController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Engineers.ToList());
    }

    public ActionResult Create()
    {
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Engineer engineer, int MachineId)
    {
      _db.Engineers.Add(engineer);
      _db.SaveChanges();
      if (MachineId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine() { MachineId = MachineId, EngineerId = engineer.EngineerId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisEngineer = _db.Engineers
          .Include(engineer => engineer.JoinEntities)
          .ThenInclude(join => join.Machine)
          .FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }

    public ActionResult Edit(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "Name");
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult Edit(Engineer engineer, int MachineId)
    {
      if (MachineId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine() { MachineId = MachineId, EngineerId = engineer.EngineerId });
      }
      _db.Entry(engineer).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      _db.Engineers.Remove(thisEngineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddMachine(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "Name");
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult AddMachine(Engineer engineer, int MachineId)
    {
      if (MachineId != 0)
      {
      _db.EngineerMachine.Add(new EngineerMachine() { MachineId = MachineId, EngineerId = engineer.EngineerId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteMachine(int joinId)
    {
      var joinEntry = _db.EngineerMachine.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
      _db.EngineerMachine.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Factory/Views/Engineers/AddMachine.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<div class="jumbotron">
<h2>Add a machine</h2>
</div>

<h4>Add a machine for this engineer: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.EngineerId)

  @Html.Label("Select machine")
  @Html.DropDownList("MachineId")

  <input type="submit" value="Save" />
}
<div id="footer">
<button style="height:100px; width:250px; font-size:20px;">@Html.ActionLink("Back to list", "Index")</button>
</div>

Factory/Views/Engineers/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<div class="jumbotron">
<h4>Add a new Engineer</h4>
</div>

<div class="row">
  <div class="col-md-4">
    <div class="card">
      @using (Html.BeginForm())
      {
        @Html.LabelFor(model => model.Name)
        <br>
        @Html.TextBoxFor(model => model.Name)
        <br>
        @Html.LabelFor(model => model.RepairMade)
        <br>
        @Html.EditorFor(model => model.RepairMade)
        <br>
        @Html.Label("Select machine")
        <br>
        @Html.DropDownList("MachineId")
        <br>
        <input type="submit" value="Add new engineer" />
      }
    </div>
  </div>
</div>
<div id="footer">
<button style="height:100px; width:250px; font-size:20px;">@Html.ActionLink("Show all engineers", "Index")</button>
</div>

Factory/Views/Engineers/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)

<div id="footer">
<button style="height:100px; width:250px; font-size:20px;">@Html.ActionLink("Back to List", "Index")</button>
</div>

Factory/Views/Engineers/Details.cshtml
@{
  Layout = "_Layout";
}

@using System;

@model Factory.Models.Engineer

<div class="jumbotron">
<h2>Engineer Details</h2>
</div>

<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>

@if(@Model.JoinEntities.Count == 0)
{
  <p>This engineer is not assigned to any machines</p>
}
else
{
  <h4>Machines assigned to @Model.Name:</h4>
  <ul>
  @foreach(var join in Model.JoinEntities)
  {
    <li>@join.Machine.Name</li>
    @using (Html.BeginForm("DeleteMachine", "Engineers"))
    {
      @Html.Hidden("joinId", @join.EngineerMachineId)
      <input type="submit" value="Delete"/>
    }
  }
  <br>
  <p>Last Repaired a machine on: @Model.RepairMade.ToString("d")</p>
  </ul>
}

<div id="footer">
<button style="height:100px; width:250px; font-size:20px;">@Html.ActionLink("Back to Engineers", "Index")</button>
<button style="height:100px; width:250px; font-size:20px;">@Html.ActionLink("Add a Machine", "AddMachine", new { id = Model.EngineerId })</button>
<button style="height:100px; width:250px; font-size:20px;">@Html.ActionLink("Edit Engineer/Log a Repair", "Edit", new { id = Model.EngineerId })</button>
<button style="height:100px; width:250px; font-size:20px;">@Html.ActionLink("Delete Engineer", "Delete", new { id = Model.EngineerId })</button>
</div>

Factory/Views/Engineers/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<div class="jumbotron">
<h2>Edit</h2>
</div>

<h4>Edit this engineer: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.EngineerId)
  <br>
  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)
  <br>
  @Html.LabelFor(model => model.RepairMade)
  @Html.EditorFor(model => model.RepairMade)
  <br>
  @Html.Label("Select machine")
  @Html.DropDownList("MachineId")
  <br>

  <input type="submit" value="Save" />
}
<hr>
<div id="footer">
<button style="height:100px; width:250px; font-size:20px;">@Html.ActionLink("Back to Engineers", "Index")</button>
</div>

Factory/Views/Engineers/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;

<div class="jumbotron">
<h1>Engineers</h1>
</div>

@if (@Model.Count == 0)
{
  <h3>No Engineers have been added yet!</h3>
} 

<ul>
  @foreach(Engineer engineer in Model)
  {
    <li>@Html.ActionLink($"{engineer.Name}", "Details", new { id = engineer.EngineerId })</li>
  }
</ul>

<div id="footer">
<button style="height:100px; width:250px; font-size:20px;">@Html.ActionLink("Home", "Index", "Home")</button>
<button style="height:100px; width:250px; font-size:20px;">@Html.ActionLink("Add new engineer", "Create")</button>
</div>